apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cba-connect-ingress
  namespace: cba-connect
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - recba.me
      secretName: recba-me-tls
  rules:
    - host: recba.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cba-ws
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cba-was
                port:
                  number: 3000
