apiVersion: v1
kind: Service
metadata:
  name: cba-was
  namespace: cba-connect
  labels:
    app: cba-was
spec:
  selector:
    app: cba-was
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
