apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: cba-connect
data:
  my.cnf: |
    [mysqld]
    character-set-server = utf8mb4
    collation-server     = utf8mb4_0900_ai_ci
    default-time-zone    = '+09:00'

    [client]
    default-character-set = utf8mb4
